# Site settings
title: outfindo.dev
email: cyril@outfindo.com
description: >- # this means to ignore newlines until "baseurl:"
  Creating great product, matching people with bikes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://outfindo.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude:
  - CNAME
  - docker-compose.yml
  - setup.sh
  - Gemfile
  - Gemfile.lock
